version: '3.8'

services:
  backend:
    build: .
    container_name: taskmanager-backend
    ports:
      - "5000:5000"
    restart: always
    env_file:
      - .env
      #- NODE_ENV=development
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  mongo:
    image: mongo:6
    container_name: taskmanager-db
    ports:
      - "27016:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:

