version: "3.8"

services:
  auth-db:
    image: postgres:15
    container_name: auth-db
    restart: always
    environment:
      POSTGRES_USER: authuser
      POSTGRES_PASSWORD: authpass
      POSTGRES_DB: authdb
    ports:
      - 5432:5432
    volumes:
      - auth_data:/var/lib/postgresql/data
    networks:
      - authnet

  auth-service:
    build:
      context: ./auth-service
    env_file: ./auth-service/.env
    container_name: auth-service
    ports:
      - "5000:5000"
    restart: unless-stopped
    depends_on:
      - auth-db
    networks:
      - authnet
      - queuenet
    volumes:
      - ./auth-service:/usr/src/app

  mail-service:
    build:
      context: ./mail-service
    container_name: mail-service
    env_file: ./mail-service/.env
    ports:
      - "5001:5001"
    restart: unless-stopped
    networks:
      - mailnet

  queue-service:
    build:
      context: ./queue-service
    env_file: ./queue-service/.env
    container_name: queue-service
    ports:
      - "5002:5002"
    restart: unless-stopped
    networks:
      - queuenet
      - mailnet

volumes:
  auth_data:

networks:
  authnet:
  mailnet:
  queuenet:
